### ISSUE TITLE
Encoding issues when calling Perseus

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/switchboard-tool-registry#102]
Perseus was added to staging in #63 but it seems there are encoding issues. See the following link and click any "perseus" tool 

https://beta-switchboard.clarin.eu/#/vlo/https%3A%2F%2Fclarinws.informatik.uni-leipzig.de%2Fclarinwebservices%2Fsentences%2F11022%2F0000-0000-7F6E-8%2Fsentencestext%2F%3FdataproviderId%3D98/text%2Fplain/por

**Comment by emanueldima** [comment]
Indeed Perseus expects a `Windows-1252` encoding, while the switchboard sends `UTF-8`.

**Comment by andmor-** [comment]
Do we have to transcode or can Perseus be called with a different encoding?

**Comment by emanueldima** [comment]
I don't know of any option to specify the encoding in the service itself. I have to change Switchboard to do that.

**Comment by andmor-** [comment]
OK. No rush while Perseus is not in production

**Comment by emanueldima** [comment]
Replaced Perseus with the more modern Scaife Viewer
