### ISSUE TITLE
publication Text Tonsorium to production

### ISSUE THREAD

**Issue by BartJongejan** [clarin-eric/switchboard-tool-registry#142]
I am happy with the integration of "Text Tonsorium - Lemmas" on https://beta-switchboard.clarin.eu/.
Please publish it on https://switchboard.clarin.eu/ !

**Comment by andmor-** [comment]
Thank you for adding your tool to the Switchboard. We are now doing some internal review on your tool's functionality and will get back to you as soon as we finish.

**Comment by kreetrapper** [comment]
done with d90f685
