### ISSUE TITLE
Upload of multiple inputs does not seem to be implemented

### ISSUE THREAD

**Issue by BartJongejan** [clarin-eric/switchboard-tool-registry#150]
There are two indications that the Switchboard might accept multiple files to be uploaded:

(1) the text in the drop area of https://switchboard.clarin.eu/input starts with "Drop files here"
(2) There is a "multiple" option in the json file. If chosen, that would mean "This input slot accepts multiple resources."

However, the input form of the Switchboard does not allow multiple uploads or URLs.

Is this a bug, a not-yet-implemented feature, or something else?

**Comment by andmor-** [comment]
The feature is being implemented see [2.4.0](https://github.com/clarin-eric/switchboard/blob/master/Changelog.md#240---2021-10-28) and [2.4.1](https://github.com/clarin-eric/switchboard/blob/master/Changelog.md#241---2022-03-31). But it is not production ready and is still under evaluation/discussion, so it is disabled in production.

We have it enabled in the beta version: https://beta-switchboard.clarin.eu/  After you upload the first file, in the results list you have the option to upload more.

Here some relevant discussions:
https://github.com/clarin-eric/switchboard/issues/28
https://github.com/clarin-eric/switchboard/issues/154
https://github.com/clarin-eric/switchboard/issues/31
