### ISSUE TITLE
Integrate eight It-Sr-NER related tools

### ISSUE THREAD

**Issue by procesaur** [clarin-eric/switchboard-tool-registry#160]
[spaCy NEL.json]
[spaCy bilingual NEL.json]
[spaCy bilingual NER and Geoparsing.json]
[spaCy bilingual NER and NEL.json]
[spaCy bilingual NER.json]
[spaCy monolingual NER and Geoparsing.json]
[spaCy monolingual NER and NEL.json]
[spaCy monolingual NER.json]

**Comment by andmor-** [comment]
Can you confirm this is about integrating the tools into the production instance (switchboard.clarin.eu)?

**Comment by procesaur** [comment]
yes, please, integrate into the production instance.

**Comment by procesaur** [comment]
Each tool now has a graphical output with an option to download raw xml for advanced users (aside from the geoparsing tools which already outputed a map). Hope that is well enough, cheers.
