### ISSUE TITLE
Create and enforce JSON schema

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard-tool-registry#19]
The json content of all tool should be checked for validity, otherwise small typos and other errors can creep in. See for instance PR https://github.com/clarin-eric/switchboard-tool-registry/pull/18 which fixes such a bug.

**Comment by emanueldima** [comment]
See https://json-schema.org for a description of the draft and useful software.
For generating schema from a json example: https://www.jsonschema.net
Other schema generators: https://json-schema.org/implementations.html#schema-generators

**Comment by emanueldima** [comment]
work in progress: https://github.com/clarin-eric/switchboard-tool-registry/blob/tools-in-directories/spec-v1.schema.json

**Comment by emanueldima** [comment]
Schema PR: https://github.com/clarin-eric/switchboard-tool-registry/pull/24

Integration with Travis to follow.

**Comment by andmor-** [comment]
Now integrated with Travis.
Closed by c0b2dea and 8b6be6c
