### ISSUE TITLE
Add maxfilesize to JSON descriptions

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/switchboard-tool-registry#20]
Many tools have an upper limit for the files they can process. Would be good to have this documented into the JSON metadata. Then the switchboard could also use this parameter to decide whether or not a tool is applicable.

concrete example: [NLP-hub](https://github.com/clarin-eric/switchboard-tool-registry/blob/master/NLP-HUB%20(multiple%20NER%20tools).json) only supports 4000 characters

**Comment by dietervu** [comment]
Sorry, more or less a duplicate of https://github.com/clarin-eric/switchboard/issues/34

**Comment by emanueldima** [comment]
https://docs.google.com/spreadsheets/d/10z3ebZvHmaBzeWILGs7l2YxhXo1nctfFf7tXO-1O554

**Comment by emanueldima** [comment]
Added field in json description, see https://github.com/clarin-eric/switchboard-tool-registry/blob/master/tools/WebLicht%20Advanced%20Mode.json#L22 for an example

I am closing this issue and continue working on https://github.com/clarin-eric/switchboard/issues/34 for rest of the implementation.
