### ISSUE TITLE
Remove the unused "softwareType" from tool description

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard-tool-registry#52]
"Originally, it was thought to be used to further characterize a tool: a sentiment analysis tool, for instance, could be classified as qualitative because it tells you whether a given text shows a certain sentiment: angry, positive, negative, etc.; wc would be a quantitative tool, it returns numbers."

**Comment by andmor-** [comment]
I agree this doesn't seem to very useful in the current context. Merging #53 ...
