### ISSUE TITLE
[Tool] Concraft processing does not terminate when called from LRS

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/switchboard-tool-registry#9]
When processing a not overly large text file ([example](http://clarinws.informatik.uni-leipzig.de:8080/clarinwebservices/sentences/11022/0000-0000-242F-4/sentencestext/?dataproviderId=7&analysis=0&)) with the multiservice demo/Concraft, the status hangs at `IN_PROGRESS`. Perhaps there is a timeout, but if so it is set to a very high value.

Link to service: http://multiservice.nlp.ipipan.waw.pl/en/clrs?input=http://clarinws.informatik.uni-leipzig.de:8080/clarinwebservices/sentences/11022/0000-0000-242F-4/sentencestext/?dataproviderId=7&analysis=0&

Note: it does seem to work with a [very small test file](https://github.com/clarin-eric/LRS-Hackathon/raw/master/samples/resources/txt/hermes-pl.txt) ([service link](http://multiservice.nlp.ipipan.waw.pl/en/clrs?input=https://github.com/clarin-eric/LRS-Hackathon/raw/master/samples/resources/txt/hermes-pl.txt&analysis=2&)).

**Comment by andmor-** [comment]
Closing since this is not something we can resolve on the Switchboard side.
We could display a warning about processing time as suggested by Claus, but the scope of such discussion should be broader than this specific issue.
